//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OgrenciBilgiSistemi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Degerlendirme
    {
        public int DegerlendirmeID { get; set; }
        public int SinavID { get; set; }
        public int OgrenciID { get; set; }
        public double SinavNotu { get; set; }
    
        public virtual Ogrenci Ogrenci { get; set; }
        public virtual Sinav Sinav { get; set; }
    }
}
