//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OgrenciBilgiSistemi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DersAcma
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DersAcma()
        {
            this.DersAlma = new HashSet<DersAlma>();
            this.DersProgrami = new HashSet<DersProgrami>();
            this.Sinav = new HashSet<Sinav>();
        }
    
        public int DersAcmaID { get; set; }
        public string AkademikYil { get; set; }
        public string AkademikDonem { get; set; }
        public int MufredatID { get; set; }
        public int Kontenjan { get; set; }
        public int OgrElmID { get; set; }
    
        public virtual Mufredat Mufredat { get; set; }
        public virtual OgretimElemani OgretimElemani { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DersAlma> DersAlma { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DersProgrami> DersProgrami { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sinav> Sinav { get; set; }
    }
}
