//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OgrenciBilgiSistemi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DersHavuzu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DersHavuzu()
        {
            this.Mufredat = new HashSet<Mufredat>();
        }
    
        public int DersID { get; set; }
        public string DersKodu { get; set; }
        public string DersAdi { get; set; }
        public string DersDili { get; set; }
        public string DersSeviyesi { get; set; }
        public string DersTuru { get; set; }
        public int Teorik { get; set; }
        public int Uygulama { get; set; }
        public double Kredi { get; set; }
        public int ECTS { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Mufredat> Mufredat { get; set; }
    }
}
