//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OgrenciBilgiSistemi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DersAlma
    {
        public int DersAlmaID { get; set; }
        public int DersAcmaID { get; set; }
        public int OgrenciID { get; set; }
        public string Durum { get; set; }
    
        public virtual DersAcma DersAcma { get; set; }
        public virtual Ogrenci Ogrenci { get; set; }
    }
}
