//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OgrenciBilgiSistemi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class obsEntities : DbContext
    {
        public obsEntities()
            : base("name=obsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bolum> Bolum { get; set; }
        public virtual DbSet<Danismanlik> Danismanlik { get; set; }
        public virtual DbSet<Degerlendirme> Degerlendirme { get; set; }
        public virtual DbSet<DersAcma> DersAcma { get; set; }
        public virtual DbSet<DersAlma> DersAlma { get; set; }
        public virtual DbSet<DersHavuzu> DersHavuzu { get; set; }
        public virtual DbSet<Derslik> Derslik { get; set; }
        public virtual DbSet<DersProgrami> DersProgrami { get; set; }
        public virtual DbSet<Kullanici> Kullanici { get; set; }
        public virtual DbSet<Mufredat> Mufredat { get; set; }
        public virtual DbSet<Ogrenci> Ogrenci { get; set; }
        public virtual DbSet<OgretimElemani> OgretimElemani { get; set; }
        public virtual DbSet<Sinav> Sinav { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
