//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OgrenciBilgiSistemi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mufredat
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Mufredat()
        {
            this.DersAcma = new HashSet<DersAcma>();
        }
    
        public int MufredatID { get; set; }
        public int BolumID { get; set; }
        public int DersID { get; set; }
        public string AkademikYil { get; set; }
        public string AkademikDonem { get; set; }
        public int DersDonemi { get; set; }
    
        public virtual Bolum Bolum { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DersAcma> DersAcma { get; set; }
        public virtual DersHavuzu DersHavuzu { get; set; }
    }
}
