//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OgrenciBilgiSistemi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ogrenci
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ogrenci()
        {
            this.Danismanlik = new HashSet<Danismanlik>();
            this.Degerlendirme = new HashSet<Degerlendirme>();
            this.DersAlma = new HashSet<DersAlma>();
        }
    
        public int OgrenciID { get; set; }
        public int BolumID { get; set; }
        public string OgrenciNo { get; set; }
        public string Durumu { get; set; }
        public System.DateTime KayitTarihi { get; set; }
        public System.DateTime AyrilmaTarihi { get; set; }
        public string Adi { get; set; }
        public string Soyadi { get; set; }
        public string TCKimlikNo { get; set; }
        public string Cinsiyet { get; set; }
        public System.DateTime DogumTarihi { get; set; }
        public int KullaniciID { get; set; }
    
        public virtual Bolum Bolum { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Danismanlik> Danismanlik { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Degerlendirme> Degerlendirme { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DersAlma> DersAlma { get; set; }
        public virtual Kullanici Kullanici { get; set; }
    }
}
